### ISSUE TITLE
SSL_do_handshake() failed 

### ISSUE THREAD

**Issue by dimagorda** [intel/asynch_mode_nginx#35]
Hello,

I am getting an SSL handshake failure when I use asynch_mode_nginx. I am usnig nginx.QAT-sample.conf as an example.

Environment:

CentOS 7.8.2003
QAT_Engine v0.5.44
QATzip v1.0.1
OpenSSL 3.0.0-alpha3-dev
Intel Corporation DH895XCC Series QAT
Nginx-1.16.1

1. when I run openssl test for QAT Engine it looks good:
openssl engine -t -c -vvvv qat

(qat) Reference implementation of QAT crypto engine
 [RSA, DSA, DH, AES-128-CBC-HMAC-SHA1, AES-128-CBC-HMAC-SHA256, AES-256-CBC-HMAC-SHA1, AES-256-CBC-HMAC-SHA256, TLS1-PRF, HKDF, X25519, X448]
 ....

Details about issue:
2. when I test  Asynch_mode_nginx / SSL (https://serverhostname  - from browser) it returns the error in nginx log:

SSL_do_handshake() failed (SSL: error:3900008C:Provider routines::missing seed error:14000044:SSL routines::internal error) while SSL handshaking, client:

3. when I test Asynch_mode_nginx / SSL from command line -- openssl s_client -connect serverhostname:443 it returns me error:

CONNECTED(00000003)
40:77:4C:5E:7B:7F:00:00:error:SSL routines::unexpected eof while reading:ssl/record/rec_layer_s3.c:307:

4. I checked ssl certificate itself and it is good:

I used the usual nginx(Without Asynch) on the same server and ssl passed ok.

can you please help me to find out the issue?

Thanks

**Comment by yongchengmiao** [comment]
Hi @dimagorda 

I think this failure could be caused by wrong version of OpenSSL.

According to Async Mod Nginx README.
https://github.com/intel/asynch_mode_nginx

The following version of components should be used.
```
QAT driver https://01.org/intel-quickassist-technology (L.4.9.0-00008)
OpenSSL-1.1.1g
QAT engine v0.5.44
QATzip v1.0.1
```

I suggest to test Async Mode Nginx with above version components.
And we tested it with nginx.QAT-sample.conf, It works well.

Also, we tried with OpenSSL 3.0.0, the situation as following.
We are not ensure all features of Async Mode Nginx works well with OpenSSL 3.0.0.
But if you want to know detailed information about the failure,
please read the following texts and provide us more information to help us to reproduce this failure.

[About reproduce]
We can't found 3.0.0-alpha3-dev in the following link.
https://github.com/openssl/openssl/releases
So, we tried to reproduce with openssl-3.0.0-alpha2.
But QAT Engine build failed with this version.
(OpenSSL-1.1.1g didn't have this problem.)

    Global symbol "@disablables_int" requires explicit package name at /opt/atf/environments/server/source/nginx-ssl/openssl-async/util/mkerr.pl line 464.
    Execution of /opt/atf/environments/server/source/nginx-ssl/openssl-async/util/mkerr.pl aborted due to compilation errors.

[Information we need]
1.We would like to know how to get OpenSSL 3.0.0-alpha3-dev.
2.We would like to know your build parameters of OpenSSL and QAT Engine.
3.We'd like to know if you got the same the QAT Engine build failure to the above or not.
    If yes, please tell us what have you done to fix this build error.

**Comment by dimagorda** [comment]
HI yongchengmiao <https://github.com/yongchengmiao>

Thank you for your response, we will follow your suggestions about versions
and let you know result.

**Comment by zhangp8x** [comment]
No reply for a long time, this issue would be closed later.
If you have any question, please reopen this issue.
